### ISSUE TITLE
Move the website of Dedukti

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#1]
The website of Dedukti is still in the master branch. One should move the website to the Deducteam.github.io repository maybe?

**Comment by GuillaumeGen** [comment]
We should probably also redirect http://dedukti.gforge.inria.fr/ to https://deducteam.github.io/ to avoid having two copies not synchronized of the same website.

**Comment by francoisthire** [comment]
Yep, and have a README to know how to edit the website now.

2017-12-01 17:51 GMT+01:00 GuillaumeGen <notifications@github.com>:

**Comment by rlepigre** [comment]
Done.

**Comment by rlepigre** [comment]
Does anyone know how to modify the old website? How can it be accessed? We should just add a redirect to https://deducteam.github.io.

**Comment by francoisthire** [comment]
There is "Deducteam" repository on gforge. I am only a user but you should
ask Frédéric or Gilles to add you. I made the redirection but there is
problem: Now, https://deducteam.github.io/ is the website of Dedukti while
http://deducteam.gforge.inria.fr/ is the website of Deducteam...

2017-12-01 19:09 GMT+01:00 Rodolphe Lepigre <notifications@github.com>:

**Comment by GuillaumeGen** [comment]
>  I made the redirection
In fact, you referenced https://deducteam.github.io/ on the web page of Deducteam, but we can still connect to http://dedukti.gforge.inria.fr/ which is a different website (and the first we find by googling Dedukti)

**Comment by francoisthire** [comment]
But there still a problem, right? The website on github is the one of
Dedukti, not Deducteam.

2017-12-01 19:29 GMT+01:00 GuillaumeGen <notifications@github.com>:

**Comment by rlepigre** [comment]
No, that's not a problem. The page https://deducteam.github.io is the GitHub page of the team, which projects all revolve around Dedukti. So in a sense, it can be Dedukti's web page. We never actually intended to move the webpage of the team to GitHub, I think.

**Comment by rlepigre** [comment]
By the way, I spend a bit of time cleaning up the webpage style and everything. Now it should now be viewable on any device I think. And there are no weird fonts anymore. And elderly people will now be able to read the text without having to zoom in.

**Comment by francoisthire** [comment]
My concern is more about the URL that are both deducteam but one is for
Dedukti and the other is for the team...

2017-12-01 20:30 GMT+01:00 Rodolphe Lepigre <notifications@github.com>:

**Comment by rlepigre** [comment]
Yeah I got that, but the URL contains "github", it should be clear that it is only about software.
